name: TypeScript Tests

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ '**' ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        node-version: [ 18.x, 20.x ]

    steps:
    - uses: actions/checkout@v5
    
    # For pnpm projects, add this step before setup-node:
    # - name: Install pnpm
    #   uses: pnpm/action-setup@v3
    #   with:
    #     version: 8
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'  # Change to 'pnpm' or 'yarn' as needed
    
    - name: Install dependencies
      run: npm ci  # For pnpm: pnpm install --frozen-lockfile | For yarn: yarn install --frozen-lockfile
    
    - name: Run tests
      run: npm test  # For pnpm: pnpm test | For yarn: yarn test
    
    - name: Generate coverage report
      run: npm run test:coverage  # For pnpm: pnpm run test:coverage | For yarn: yarn test:coverage
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      if: matrix.os == 'ubuntu-latest' && matrix.node-version == '20.x'
      with:
        files: ./coverage/lcov.info
        flags: unittests
        fail_ci_if_error: false

